{
  "type": "record",
  "name": "OrderPlacedEvent",
  "namespace": "com.techie.microservices.order.event",
  "fields": [
    { "name": "orderNumber", "type": "string" },
    { "name": "email", "type": "string" },
    { "name": "firstName", "type": "string" },
    { "name": "lastName", "type": "string" },
    { "name": "skuCode", "type": ["null", "string"], "default": null },
    { "name": "quantity", "type": ["null", "int"], "default": null },
    { "name": "totalAmount", "type": ["null", "string"], "default": null },
    { "name": "placedAt", "type": ["null", "string"], "default": null }
  ]
}
