spring.application.name=product-service
spring.datasource.url=${PRODUCT_DB_URL:jdbc:mysql://localhost:3306/product_service}
spring.datasource.username=${PRODUCT_DB_USERNAME:root}
spring.datasource.password=${PRODUCT_DB_PASSWORD:${MYSQL_ROOT_PASSWORD:}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

#URL: http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html

#URL: http://localhost:8080/api-docs
springdoc.api-docs.path=/api-docs

# Actuator EndPoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized

# Metrics
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=product-service

# Tracing
management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:0.1}
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

# Logging Pattern with Trace IDs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} [%X{traceId:-},%X{spanId:-}] - %msg%n
logging.level.root=INFO
